#!/bin/sh

case "$1" in
    start)
        echo "Starting thermostat client"
        /usr/sbin/thermostat_client
        ;;

    stop)
        echo "Stopping thermostat client"
        killall thermostat_client 2>/dev/null
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
